Responsividade
EsdrasAlbino/crew pull request #11
Opened 2023-09-18 15:00 UTC by MariaFFA

2023-09-20 11:59 UTC, weltonfelix requested changes

2023-09-20 11:59 UTC, weltonfelix commented on entities/crew_entity.py
> +        self.screen_width, self.screen_height = info.current_w, info.current_h
```suggestion
        self.screen_dimensions = (info.current_w, info.current_h)
```

Pode ser legal juntar essas variáveis numa tupla.

2023-09-20 11:59 UTC, weltonfelix commented on entities/crew_entity.py
> +        self.window_width, self.window_height = self.screen.get_size()
```suggestion
        self.window_dimensions = self.screen.get_size()
```

2023-09-20 11:59 UTC, weltonfelix commented on entities/crew_entity.py
> +        self.fullscreen = False
```suggestion
        self.is_fullscreen = False
```
O "is" deixa mais claro que é um booleano. Talvez seja útil.

2023-09-20 11:59 UTC, weltonfelix commented on entities/crew_entity.py
> +        pygame.display.set_caption("Crew")
```suggestion
        pygame.display.set_caption(GAME_TITLE)
```
Essas strings podem ser definidas como uma constante no topo do documento, pra facilitar a edição.

2023-09-20 11:59 UTC, weltonfelix commented on entities/crew_entity.py
> +            track_left = self.window_width // 2 - self.window_height // 2
O que é o track left? A margem? A coordenada?
Pode ser interessante colocar `track_left_coord` ou `track_margin_left`.

2023-09-20 11:59 UTC, weltonfelix commented on assets/Fundo Espacial.jpg
Tenta manter os nomes dos arquivos no padrão, em inglês, minúsculo e sem caracteres especiais. Algo como `background.jpg`.

2023-09-20 11:59 UTC, weltonfelix commented on entities/crew_entity.py
> +        asteroid_height = (track_right - track_left) / 10
Pode ser legal agrupar numa tupla. Com isso, ao invés de passar `(asteroid_width, asteroid_height)` para o `scale`, já poderia passar a tupla direto. Além de deixar o código menos verboso.

2023-09-20 11:59 UTC, weltonfelix commented on entities/crew_entity.py
> +        asteroid_height = (track_right - track_left) / 10
A mesma coisa para os outros objetos.

2023-09-20 11:59 UTC, weltonfelix commented on entities/crew_entity.py
> +        running = True
Pelo mesmo motivo do outro booleano, pode ser interessante adicionar o is.
```suggestion
        is_running = True
```

2023-09-20 11:59 UTC, weltonfelix commented on entities/crew_entity.py
> +                spacecraft_width,
Ao invés de passar essa grande quantidade de variáveis, pode usar uma tupla para cada objeto, como:

```
propellant_dimensions = (propellant_width, propellant_height)
propellant_coords = ...
propellant_data = (propellant, propellant_dimensions, propellant_coords)
```

2023-09-20 11:59 UTC, weltonfelix commented on util/change_window_size_util.py
> +def change_size_window(screen, window_width, spacecraft_left, propellant_left, bullet_left, comet_left):
```suggestion
def change_window_size(screen, window_width, spacecraft_left, propellant_left, bullet_left, comet_left):
```

2023-09-20 11:59 UTC, weltonfelix commented on util/change_window_size_util.py
> +    return window_width, window_height, track_right, track_left, track_botton, track_top, background, asteroid, asteroid_width, asteroid_height, asteroid_left, spacecraft, spacecraft_width, spacecraf
Da mesma forma, esses retornos podem ser agrupados em tuplas para facilitar a leitura do código.

2023-09-22 00:23 UTC, EsdrasAlbino approved these changes

2023-09-22 01:38 UTC, weltonfelix approved these changes
LGTM. @MariaFFA você consegue checar se as mudanças do meu último commit continuam produzindo o resultado esperado? Se sim, pode fazer o squash and merge.

2023-09-22 11:30 UTC, MathBorgess approved these changes
LGTM

2023-09-22 11:31 UTC, merged