Feature/initial screen
EsdrasAlbino/crew pull request #12
Opened 2023-09-20 10:49 UTC by MathBorgess

2023-09-20 12:38 UTC, weltonfelix requested changes

2023-09-20 12:38 UTC, weltonfelix commented on entities/crew_entity.py
> +                self.current_screen = self.current_screen.run(self.screen, self.screen_size, event)
Adicionar uma linha em branco no final do arquivo,

2023-09-20 12:38 UTC, weltonfelix commented on entities/initial_screen_entity.py
> +
Colocar as constantes como globais e não como propriedades da classe.

2023-09-20 12:38 UTC, weltonfelix commented on entities/initial_screen_entity.py
> +        self.credits_button_rect = self.credits_button.get_rect(center=(screen_size[0] // 2, screen_size[1] // 2 + 100))
Colocar `_` nas propriedades privadas.

2023-09-20 12:38 UTC, weltonfelix commented on entities/initial_screen_entity.py
> +        still_showing = True
Algo como `is_visible` pode ser mais descritivo.

2023-09-22 11:15 UTC, weltonfelix approved these changes
LGTM

2023-09-22 11:16 UTC, MariaFFA approved these changes

2023-09-22 11:16 UTC, tuliooarauj approved these changes

2023-09-22 11:47 UTC, merged