Feature/collision
EsdrasAlbino/crew pull request #13
Opened 2023-09-22 11:34 UTC by tuliooarauj

2023-09-22 12:12 UTC, EsdrasAlbino reviewed
Muda o nome dos arquivos de image

Fundo Espacial -> background 
Nave Completa -> playerFull
Propulsor-2 -> propellant
comet-3 -> comet

2023-09-22 12:22 UTC, EsdrasAlbino approved these changes
LGTM

2023-09-22 18:36 UTC, EsdrasAlbino commented on entities/player_entity.py
> +        self.image = pygame.image.load("assets/player.png")
Criar constante para imagens, de preferência em um arquivo de path que fique em util

2023-09-22 23:51 UTC, weltonfelix requested changes
Pequenas melhorias.

2023-09-22 23:51 UTC, weltonfelix commented on .vscode/settings.json
Remover este arquivo e adicionar `.vscode` ao `.gitignore`.

2023-09-22 23:51 UTC, weltonfelix commented on entities/__init__.py
Remover arquivo.

2023-09-22 23:51 UTC, weltonfelix commented on entities/crew_entity.py
> +
```suggestion
```

2023-09-22 23:51 UTC, weltonfelix commented on entities/player_entity.py
> +from typing import Tuple
Remover import não utilizado.
```suggestion
```

2023-09-22 23:51 UTC, weltonfelix commented on __main__.py
> +
```suggestion
```

2023-09-22 23:51 UTC, weltonfelix commented on entities/crew_entity.py
>  import pygame
Reordenar imports

```suggestion
import pygame
from entities.initial_screen_entity import StartScreen
```

2023-09-23 09:01 UTC, MathBorgess commented on entities/bullet_entity.py
Coloca esse tuple (150, 200, 255) de cor como uma variável global e descreve sua cor

2023-09-23 09:01 UTC, MathBorgess commented on entities/player_entity.py
> +        self.bullet_velocity = 5
Coloca a bullet_velocity e cooldown como constantes globais

2023-09-23 09:01 UTC, MathBorgess commented on entities/throttle_entity.py
> +            self.__player.cooldown /= 4
setta o valor que o cooldown vai cais como uma variável tbm

2023-09-23 16:45 UTC, weltonfelix approved these changes
LGTM

2023-09-23 18:01 UTC, MariaFFA approved these changes

2023-09-23 19:23 UTC, merged