Feature/inventory
EsdrasAlbino/crew pull request #16
Opened 2023-09-23 00:04 UTC by EsdrasAlbino

2023-09-23 01:00 UTC, weltonfelix requested changes

2023-09-23 01:00 UTC, weltonfelix commented on entities/inventory_entity.py
> +        item_spacing = 20
Colocar *magic numbers* em variáveis globais

2023-09-23 01:00 UTC, weltonfelix commented on entities/inventory_entity.py
> +        x, y = item_spacing, item_spacing
```suggestion
        position = (item_spacing, item_spacing)
```

2023-09-23 01:00 UTC, weltonfelix commented on entities/inventory_entity.py
> +        top_right_x = screen_width - item_spacing - 70
Colocar `70` numa variável global descritiva.

2023-09-23 01:00 UTC, weltonfelix commented on entities/item_entity.py
> +        self.image = pygame.Surface((30, 30))
Colocar as dimensões em variáveis globais.
```
ITEM_WIDTH=30
ITEM_HEIGHT=30
```

2023-09-23 01:00 UTC, weltonfelix commented on entities/item_entity.py
> +        variation_position = 35
Colocar `35` em uma variável global descritiva.

2023-09-23 01:00 UTC, weltonfelix commented on entities/item_entity.py
> +    def draw(self, surface, x, y):
```suggestion
    def draw(self, surface, position):
```

2023-09-23 01:00 UTC, weltonfelix commented on entities/life_entity.py
> +#        pygame.game.screen.blit(self.image, self.rect)
Remover código não utilizado.
```suggestion
```

2023-09-23 01:00 UTC, weltonfelix commented on entities/life_entity.py
> +        self.image = pygame.transform.scale(self.image, (23, 23))
Colocar *magic numbers* em variáveis globais.

2023-09-23 01:00 UTC, weltonfelix commented on entities/life_entity.py
> +    def __init__(self, xpos, ypos):
```suggestion
    def __init__(self, position):
```

2023-09-23 01:00 UTC, weltonfelix commented on util/images_render.py
> +from paths import IMAGE_PATH
De onde é esse import?

2023-09-23 08:55 UTC, MathBorgess commented on entities/crew_entity.py
O ideal é que o inventário fosse setado dentro da própria game_entity, já que ele não será utilizado em qualquer outra tela

2023-09-23 14:17 UTC, EsdrasAlbino commented on entities/crew_entity.py
Não necessariamente, ele seria utilizado na menu screen?

2023-09-23 14:29 UTC, EsdrasAlbino commented on entities/inventory_entity.py
> +        x, y = item_spacing, item_spacing
Isso aqui não pode ser uma tupla, no máximo, posso tornar uma array

2023-09-23 14:32 UTC, EsdrasAlbino commented on util/images_render.py
> +from paths import IMAGE_PATH
Eu criei esse arquivo para pegar paths globais, mas foi excluído

2023-09-23 17:29 UTC, MathBorgess commented on entities/crew_entity.py
> +            inventory.add_item(item)
Seria melhor só setar esses dados iniciais quando o usuário abrir o game_entity, não?

2023-09-23 17:58 UTC, weltonfelix approved these changes

2023-09-26 20:39 UTC, MariaFFA approved these changes

2023-09-27 02:26 UTC, tuliooarauj approved these changes

2023-09-27 12:11 UTC, merged