Feature/race track
EsdrasAlbino/crew pull request #8
Opened 2023-09-18 12:23 UTC by MathBorgess

Racetrack with acceleration feature, and controls the y-axis movement

2023-09-18 12:41 UTC, weltonfelix requested changes
Alguns typos e mudanças menores.

2023-09-18 12:41 UTC, weltonfelix commented on .vscode/settings.json
> +}
```suggestion

```

2023-09-18 12:41 UTC, weltonfelix commented on entities/racetrack_entity.py
> +    def __init__(self, accelaration, max_speed, friction, spaceship, screen):
```suggestion
    def __init__(self, acceleration, max_speed, friction, player, screen):

```

2023-09-18 12:41 UTC, weltonfelix commented on entities/racetrack_entity.py
> +        self.accelaration = accelaration
```suggestion
        self.acceleration = acceleration

```

2023-09-18 12:41 UTC, weltonfelix commented on entities/racetrack_entity.py
> +        self.speed = 2  # Initial speed
```suggestion
        self.speed = INITIAL_SPEED # Initial speed

```

Pode ser melhor definir isso como uma constante lá em cima

2023-09-18 12:41 UTC, weltonfelix commented on entities/racetrack_entity.py
> +    def get_visible_colliders(self):
Tenta usar os getters e setters do python https://realpython.com/python-getter-setter/

2023-09-18 12:41 UTC, weltonfelix commented on entities/racetrack_entity.py
> +    def get_colliderect(self):
```suggestion
    def get_collision_rect(self):

```
Tenta usar getter

2023-09-20 10:48 UTC, MathBorgess commented on entities/racetrack_entity.py
> +    def get_visible_colliders(self):
done

2023-09-20 12:00 UTC, weltonfelix approved these changes
LGTM

2023-09-20 13:12 UTC, MariaFFA approved these changes

2023-09-20 13:18 UTC, EsdrasAlbino approved these changes

2023-09-20 14:17 UTC, merged